import{decorateCta as e,fetchAndProcessPlainHtml as t,getActiveLink as a,getAnalyticsValue as n,icons as s,isDesktop as i,logErrorFor as r,selectors as l,setActiveDropdown as o,toFragment as c,trigger as d,yieldToMain as m,addMepHighlightAndTargetId as p,getAsyncDropdownCount as u,setActiveLink as f,getDisableAEDState as v,hasActiveLink as h}from"../utilities.js";const g=(e,t)=>{if(!(e instanceof HTMLElement))return null;const a=c`<div class="feds-menu-headline">
      ${e.textContent.trim()}
    </div>`,s=e=>{i.matches||(d({element:a,event:e,type:"headline"}),o(a))},r=()=>{i.matches?(a.setAttribute("role","heading"),a.removeAttribute("tabindex"),a.setAttribute("aria-level",2),a.removeAttribute("aria-haspopup",!0),a.removeAttribute("aria-expanded",!1),a.removeAttribute("daa-ll"),a.removeEventListener("click",s)):(a.setAttribute("role","button"),a.setAttribute("tabindex",0),a.removeAttribute("aria-level"),a.setAttribute("aria-haspopup",!0),a.setAttribute("aria-expanded",!1),a.setAttribute("daa-ll",n(a.textContent,t)),a.addEventListener("click",s))};return r(),i.addEventListener("change",r),e.remove(),a},$=(e,t)=>{if(!(e instanceof HTMLElement&&e.querySelector("a")))return"";const a=e.querySelector("picture"),s=e.querySelector("a"),i=e.querySelector("p:nth-child(2)"),r=[...e.classList].filter((e=>"link-group"!==e)).map((e=>`feds-navLink--${e}`)),l=a?c`<div class="feds-navLink-image">${a}</div>`:"",o=i?c`<div class="feds-navLink-description">${i.textContent}</div>`:"",d=s?c`<div class="feds-navLink-content">
      <div class="feds-navLink-title">${s.textContent}</div>
      ${o}
    </div>`:"";let m=c`<a
    href="${s.href}"
    class="feds-navLink${r.length?` ${r.join(" ")}`:""}"
    daa-ll="${n(s.textContent,t)}">
      ${l}
      ${d}
    </a>`;return m.classList.contains("feds-navLink--header")&&(m=c`<div
      role="heading"
      aria-level="3"
      class="feds-navLink${r.length?` ${r.join(" ")}`:""}"
      daa-ll="${n(s.textContent,t)}">
        ${l}
        ${d}
      </div>`),s?.target&&(m.target=s.target),m},y=({elem:t,className:a="feds-navLink",itemIndex:s={position:0}}={})=>{const i=t=>{if(s.position+=1,t.matches(".link-group"))return $(t,s.position);if("STRONG"===t.parentElement.tagName||"EM"===t.parentElement.tagName){const a="EM"===t.parentElement.tagName?"secondaryCta":"primaryCta";return t.parentElement.replaceWith(t),e({elem:t,type:a,index:s.position})}return t.setAttribute("daa-ll",n(t.textContent,s.position)),t.classList.add(a),t},r="a, .link-group";return t.matches(r)?c`<li>${i(t)}</li>`:(t.querySelectorAll(r).forEach((e=>{e.replaceWith(i(e))})),t)},L=e=>{const t=e.querySelector("a"),a=e.querySelector("picture"),n=t instanceof HTMLElement?c`<a class="feds-image" href="${t.href}" daa-ll="gnav-image">${a}</a>`:c`<div class="feds-image">${a}</div>`;return e.replaceChildren(n),c`<div class="feds-image-wrapper">${e}</div>`},E=(e,t)=>{const a=e.matches(".dark"),n=e.matches(".image-only"),s=e.querySelector("p > strong"),i=e.querySelector("picture");if(!n){const t=[...e.querySelectorAll(":scope > div")].find((e=>!(e.querySelector("picture")instanceof HTMLElement)));t?.classList.add("feds-promo-content")}if(s?.textContent.trim()){const e=c`<h2 class="feds-promo-header">
        ${s.textContent.trim()}
      </h2>`;s.parentElement.replaceWith(e)}y({elem:e,className:"feds-promo-link",index:t});return i instanceof HTMLElement&&(()=>{const t=e.querySelector("a"),a=i.closest(`${l.gnavPromo} > div`);let s;s=t instanceof HTMLElement?c`<a class="feds-promo-image" href="${t.href}" daa-ll="promo-image">
          ${i}
        </a>`:c`<div class="feds-promo-image">
          ${i}
        </div>`,n?e.replaceChildren(s):a?.replaceWith(s)})(),e.classList="feds-promo",a&&e.classList.add("feds-promo--dark"),c`<div class="feds-promo-wrapper" daa-lh="promo-card">
      ${e}
    </div>`},S=async({content:e,separatorTagName:t="H5"}={})=>{const a=e.children.length>1;let s=0;for await(const i of[...e.children]){await m();const e=a?"feds-menu-column":"feds-menu-content",r=a?"feds-menu-section":"feds-menu-column",o=c`<div class="${e}"></div>`;let d,p=c`<div class="${r}"></div>`;const u={position:0},f=()=>{p.childElementCount&&o.append(p),p=c`<div class="${r}"></div>`};for(;i.children.length;){await m();const r=i.firstElementChild;if(r.matches(l.columnBreak))f(),r.remove();else if(r.tagName===t){s+=1,f(),a||(u.position=0);const t=g(r,s);if(d=c`<div class="feds-menu-items" daa-lh="${n(t.textContent.trim())}"></div>`,p.append(t,d),i.querySelector(l.columnBreak)){o.classList.add(`${e}--group`),i.querySelectorAll(l.columnBreak).length>1&&o.classList.add(`${e}--wide`);const t=document.createElement("div");t.append(...i.childNodes),d.append(t),await S({content:d})}}else if(r.matches(l.gnavPromo)){f(),u.position=0;const e=E(r,u);p.append(e)}else if(r.matches(".gnav-image")){f(),u.position=0;const e=L(r);p.append(e)}else{let e=y({elem:r,itemIndex:u});r.remove();const t=d||p;let a=null;if("P"===e.tagName&&(e=c`<li>${e.innerHTML}</li>`),"LI"===e.tagName){let e=t.querySelector("ul");e||(e=c`<ul></ul>`,t.append(e)),a=e}else a=t;a.append(e)}}o.append(p),i.replaceWith(o)}};let k=0;export default{decorateMenu:e=>r((async()=>{let n;if("syncDropdownTrigger"===e.type){const t=e.item.closest("div"),a=t.querySelector("h2");t.removeChild(a),n=c`<div class="feds-popup">
        ${t}
      </div>`,await S({content:n})}if("asyncDropdownTrigger"===e.type){performance.mark(`DecorateMenu-${k}-Start`);const r=e.item.querySelector("a");if(!(r instanceof HTMLElement))return;const o=await t({url:r.href});if(!o)return;const d=c`<div class="feds-menu-content">${o.innerHTML}</div>`;if(n=c`<div class="feds-popup">
        <div class="feds-menu-container">
          ${d}
        </div>
      </div>`,p(n,o),(e=>{const t=e.querySelector(".cross-cloud-menu");t&&(y({elem:t}),t.className="feds-crossCloudMenu-wrapper",t.querySelector("div").className="feds-crossCloudMenu",t.querySelectorAll("ul li").forEach(((e,t)=>{0===t&&e.querySelector("a")?.prepend(c`${s.home}`),e.className="feds-crossCloudMenu-item"})),e.append(t))})(n),await S({content:d}),a(n)instanceof HTMLElement){const t=()=>{e.template.style.width="",e.template.classList.remove(l.deferredActiveNavItem.slice(1))};e.template.classList.add(l.activeNavItem.slice(1)),i.matches&&(e.template.style.width=`${e.template.offsetWidth}px`,e.template.classList.add(l.deferredActiveNavItem.slice(1)),i.addEventListener("change",t,{once:!0}),window.addEventListener("feds:navOverflow",t,{once:!0}))}if(k+=1,e.template.classList.add("feds-navItem--megaMenu"),u()===k&&!h()){const e=document.querySelectorAll(".feds-nav .feds-navItem--megaMenu");v()||1!==e.length||(e[0].classList.add(l.activeNavItem.slice(1)),f(!0))}}"footerMenu"===e.type&&await S({content:e.item,separatorTagName:"H2"}),e.template?.querySelector(".feds-popup.loading")?.remove(),e.template?.append(n),"asyncDropdownTrigger"===e.type&&performance.mark(`DecorateMenu-${k}-End`)}),"Decorate menu failed","gnav-menu","i"),decorateLinkGroup:$,decorateHeadline:g};