// spectrum2 manifest: what the loader resolves.
// members: block name -> its family folder under blocks/ (a name that differs from its
//   family has a stub under alias/).
// skins: css that restyles a milo block on the page, and the <body> class that gates it.
// neutral: metadata-style blocks that never render.
// miloBlocks: milo's own block names (libs/blocks).
export default {
  members: {
    accordion: 'faq',
    'action-item': 'quick-actions',
    'action-scroller': 'quick-actions',
    'article-feed': 'recommended-articles',
    'article-header': 'article-header',
    aside: 'aside',
    'base-card': 'base-card',
    'bento-tiles': 'bento-tiles',
    'blog-author': 'blog-author',
    brick: 'explore-card',
    card: 'base-card',
    'card-horizontal': 'base-card',
    carousel: 'carousel',
    chart: 'chart',
    'cinematic-stage': 'cinematic-stage',
    columns: 'columns',
    'customer-story': 'customer-story',
    'editorial-card': 'base-card',
    'editorial-index': 'editorial-index',
    'event-speakers': 'event-speakers',
    'explore-card': 'explore-card',
    faq: 'faq',
    'feature-rows': 'feature-rows',
    figure: 'figure',
    'hero-marquee': 'hero-marquee',
    'how-to': 'how-to',
    'icon-block': 'icon-block',
    'logo-wall': 'logo-wall',
    marquee: 'hero-marquee',
    'marquee-anchors': 'hero-marquee',
    media: 'media',
    notification: 'aside',
    'product-explorer': 'product-explorer',
    'quick-actions': 'quick-actions',
    'quick-facts': 'quick-facts',
    quote: 'social-proof',
    'recommended-articles': 'recommended-articles',
    'rich-content': 'rich-content',
    'social-proof': 'social-proof',
    'stage-hero': 'stage-hero',
    stats: 'quick-facts',
    table: 'table',
    tabs: 'tabs',
    text: 'rich-content',
    'tree-view': 'tree-view',
    video: 'video',
    'z-pattern': 'media',
  },
  skins: [
    {
      name: 'brand-concierge-skin',
      skinOf: 'brand-concierge',
      activation: 'page',
      gate: 'brand-concierge-skin',
    },
    {
      name: 'caas-skin',
      skinOf: 'caas',
      activation: 'page',
      gate: 'caas-skin',
    },
    {
      name: 'form-skin',
      skinOf: 'marketo',
      activation: 'page',
      gate: 'form-skin',
    },
    {
      name: 'modal-skin',
      skinOf: 'modal',
      activation: 'page',
      gate: 'modal-skin',
    },
    {
      name: 'prose-skin',
      skinOf: 'default-content',
      activation: 'all-spectrum2',
      gate: 'prose-skin',
    },
    {
      name: 'section-skin',
      skinOf: 'section-metadata',
      activation: 'page',
      gate: 'section-skin',
    },
  ],
  neutral: [
    'section-metadata',
    'fragment',
    'modal-metadata',
    'card-metadata',
    'caas-marquee-metadata',
    'metadata',
  ],
  defaultTheme: 'c2.92dbaacf',
  themes: { 'c2.92dbaacf': 'themes/spectrum2-tokens.c2.92dbaacf.css' },
  channels: { 'reimagine/c2': 'c2.92dbaacf' },
  sets: {
    'reimagined-acom.f09d4fb7': {
      members: [
        'rich-content',
        'text',
      ],
      skins: {
        'brand-concierge-skin': {
          'brand-concierge': {
            add: [
              'stage',
            ],
            drop: [
              'stage-split',
              'stage-daylight',
              'stage-paper',
              'stage-gallery',
              'stage-twilight',
            ],
          },
        },
      },
    },
  },
  miloBlocks: [
    'accordion',
    'action-item',
    'action-scroller',
    'adobetv',
    'article-feed',
    'article-header',
    'aside',
    'author-header',
    'base-card',
    'blog-author',
    'brand-concierge',
    'brand-concierge-global',
    'brick',
    'bulk-publish',
    'bulk-publish-v2',
    'caas',
    'caas-config',
    'caas-marquee',
    'caas-marquee-metadata',
    'card',
    'card-horizontal',
    'card-metadata',
    'carousel',
    'carousel-c2',
    'chart',
    'columns',
    'comparison-table',
    'comparison-table-c2',
    'editorial-card',
    'elastic-carousel',
    'email-collection',
    'email-collection-c2',
    'explore-card',
    'faas',
    'faq',
    'featured-article',
    'figure',
    'firefly-globe',
    'floating-cta',
    'footer',
    'form',
    'fragment',
    'gist',
    'global-footer',
    'global-navigation',
    'globe-gallery',
    'gnav',
    'graybox',
    'hero-marquee',
    'hover-list',
    'how-to',
    'hub-hero',
    'icon-block',
    'iframe',
    'instagram',
    'language-banner',
    'language-selector',
    'locui',
    'locui-create',
    'logo-ticker',
    'm7',
    'market-selector',
    'marketo',
    'marketo-config',
    'marquee',
    'marquee-anchors',
    'martech-metadata',
    'mas-compare-chart-autoblock',
    'media',
    'merch',
    'merch-card',
    'merch-card-autoblock',
    'merch-card-collection-autoblock',
    'merch-offers',
    'mmm',
    'mnemonic-list',
    'mobile-app-banner',
    'modal',
    'modal-metadata',
    'news',
    'notification',
    'nps-csat-form',
    'offer-hero',
    'pdf-space',
    'pdf-viewer',
    'pill-group',
    'plans-hero',
    'preflight',
    'product-marquee-grid',
    'promo',
    'quick-actions',
    'quick-facts',
    'quiz',
    'quiz-entry',
    'quiz-marquee',
    'quiz-results',
    'quote',
    'read-more',
    'reading-time',
    'recommended-articles',
    'region-nav',
    'review',
    'rich-content',
    'roller-carousel',
    'router-marquee',
    'section-metadata',
    'share',
    'side-by-side',
    'slideshare',
    'social-proof',
    'split-aside-grid',
    'susi-light-login',
    'table',
    'table-metadata',
    'table-of-contents',
    'tabs',
    'tag-selector',
    'tags',
    'text',
    'tiktok',
    'timeline',
    'tour',
    'twitter',
    'video',
    'vimeo',
    'visually-hidden',
    'walls-io',
    'youtube',
    'z-pattern',
  ],
};
