module.exports = {
  name: 'Marquee Block',
  features: [
    {
      tcid: '0',
      name: '@Marquee (light)',
      path: '/drafts/nala/blocks/marquee/marquee-light',
      data: {
        h2Text: 'Heading XL Marquee standard medium left light',
        bodyText: 'Body M Lorem ipsum dolor sit amet,',
        outlineButtonText: 'Lorem ipsum',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-light @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@Marquee (small)',
      path: '/drafts/nala/blocks/marquee/marquee-small',
      data: {
        h2Text: 'Marquee standard small dark',
        bodyText: 'Lorem ipsum dolor sit amet',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-small @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@Marquee (small,light)',
      path: '/drafts/nala/blocks/marquee/marquee-small-light',
      data: {
        detailText: 'Detail',
        h2Text: 'Heading XL Marquee standard small light',
        bodyText: 'Lorem ipsum dolor sit amet',
        outlineButtonText: 'Lorem ipsum',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-small-light @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@Marquee (large)',
      path: '/drafts/nala/blocks/marquee/marquee-large',
      data: {
        h2Text: 'Marquee Large Dark',
        bodyText: 'Lorem ipsum dolor sit amet',
        outlineButtonText: 'Lorem ipsum',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-large @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@Marquee (large,light)',
      path: '/drafts/nala/blocks/marquee/marquee-large-light',
      data: {
        h2Text: 'Marquee Large Light',
        bodyText: 'Lorem ipsum dolor sit amet',
        outlineButtonText: 'Secondary action',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-large-light @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@Marquee (quiet)',
      path: '/drafts/nala/blocks/marquee/marquee-quiet',
      data: {
        detailText: 'Detail',
        h2Text: 'Marquee quiet',
        bodyText: 'Marquee’s variants are small,',
        blueButtonText: 'Watch the video',
      },
      tags: '@marquee @marquee-quiet @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@Marquee (inline)',
      path: '/drafts/nala/blocks/marquee/marquee-inline',
      data: {
        detailText: 'Detail',
        h2Text: 'Marquee inline',
        bodyText: 'Marquee’s variants are small,',
      },
      tags: '@marquee @marquee-inline @smoke @regression @milo',
    },
    {
      tcid: '7',
      name: '@Marquee (split,small)',
      path: '/drafts/nala/blocks/marquee/marquee-split-small',
      data: {
        detailText: 'DETAIL M BOLD 12/15 OPTIONAL',
        h2Text: 'Marquee Split ½ dark',
        bodyText: 'Lorem ipsum dolor sit amet',
        outlineButtonText: 'Secondary action',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-split-small @smoke @regression @milo',
    },
    {
      tcid: '8',
      name: '@Marquee (split,large)',
      path: '/drafts/nala/blocks/marquee/marquee-split-large',
      data: {
        detailText: 'DETAIL L BOLD 16/20',
        h2Text: 'Heading XXL 44/55 Lorem',
        bodyText: 'Body XL Regular (22/33) Lorem ipsum dolor sit amet',
        blueButtonText: 'Call to action',
        linkText: 'Body M 18/27',
      },
      tags: '@marquee @marquee-split-large @smoke @regression @milo',
    },
    {
      tcid: '9',
      name: '@Marquee (split,one-third,large,light)',
      path: '/drafts/nala/blocks/marquee/marquee-split-one-third-large-light',
      data: {
        detailText: 'DETAIL L BOLD 16/20',
        h2Text: 'Heading XXL 44/55 Lorem',
        bodyText: 'Body XL Regular (22/33) Lorem ipsum dolor sit amet',
        blueButtonText: 'Call to action',
        linkText: 'Body M 18/27',
      },
      tags: '@marquee @marquee-split-one-third-large-light @smoke @regression @milo',
    },
    {
      tcid: '10',
      name: '@Marquee (split,one-third)',
      path: '/drafts/nala/blocks/marquee/marquee-split-one-third',
      data: {
        detailText: 'DETAIL M BOLD 12/15 OPTIONAL',
        h2Text: 'Heading XL 36/45 Lorem',
        bodyText: 'Body M Regular (18/27) Lorem ipsum dolor sit amet',
        blueButtonText: 'Call to action',
        linkText: 'Body M 18/27',
      },
      tags: '@marquee @marquee-split-one-third @smoke @regression @milo',
    },
    {
      tcid: '11',
      name: '@Marquee (split,one-third,small,light)',
      path: '/drafts/nala/blocks/marquee/marquee-split-one-third-small-light',
      data: {
        detailText: 'DETAIL M BOLD 12/15 OPTIONAL',
        h2Text: 'Heading XL 36/45 Lorem',
        bodyText: 'Body M Regular (18/27) Lorem ipsum dolor sit amet',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-split-one-third-small-light @smoke @regression @milo',
    },
    {
      tcid: '12',
      name: '@Marquee small (background video playsinline)',
      path: '/drafts/nala/blocks/marquee/marquee-small-background-video',
      data: {
        h2Text: 'Marquee standard small dark',
        bodyText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        blueButtonText: 'Call to action',
      },
      tags: '@marquee @marquee-video @smoke @regression @milo',
    },
    {
      tcid: '13',
      name: '@Marquee large (background video playsinline desktop)',
      path: '/drafts/nala/blocks/marquee/marquee-large-desktop-video-autoplay',
      data: {
        h2Text: 'Desktop video only',
        bodyText: 'From amazing AI-generated images in Photoshop',
        blueButtonText: 'Free trial',
        linkText: 'See all plans',
      },
      tags: '@marquee @marquee-video @smoke @regression @milo',
    },
    {
      tcid: '14',
      name: '@Marquee large (background video playsinline loop once)',
      path: '/drafts/nala/blocks/marquee/video-autoplay-loop-once',
      data: {
        detailText: 'DETAIL L 16/20',
        h2Text: 'Heading XL 36/45 Media (large, dark)',
        bodyText: 'Body M 18/27 Lorem ipsum dolor sit amet',
        blueButtonText: 'Learn More',
      },
      tags: '@marquee @marquee-video @smoke @regression @milo',
    },
  ],
};
