/* eslint-disable max-len */

module.exports = {
  FeatureName: 'Merch Card Block',
  features: [
    {
      tcid: '0',
      name: '@Merch-card (Segment)',
      path: '/drafts/nala/blocks/merch-card/merch-card-segment',
      data: {
        title: 'Individuals',
        price: 'US$59.99/mo',
        strikethroughPrice: 'US$89.99/mo',
        description: 'Save over 25% on 20+ apps, including Photoshop, Illustrator, and more. First year only. Ends 27',
        link1Text: 'See what\'s included',
        link2Text: 'Learn more',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@Merch-card (Segment) with Badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-segment-with-badge',
      data: {
        title: 'Individuals',
        badgeText: 'Best value',
        price: 'US$59.99/mo',
        strikethroughPrice: 'US$89.99/mo',
        description: 'Save over 25% on 20+ apps, including Photoshop, Illustrator, and more. First year only. Ends 27',
        link1Text: 'See what\'s included',
        link2Text: 'Learn more',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@Merch-card (special-offers) ',
      path: '/drafts/nala/blocks/merch-card/merch-card-special-offers',
      data: {
        titleH4: 'INDIVIDUALS',
        titleH3: 'Save over 30% on Creative Cloud All Apps.',
        description1: 'Get 20+ creative apps and save big when you choose a yearly plan instead of a monthly plan.',
        description2: 'Create gorgeous images, rich graphics, and incredible art. Save 10% for the first year. Ends Mar 20.',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@Merch-card (special-offers) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-special-offers-with-badge',
      data: {
        titleH4: 'INDIVIDUALS',
        titleH3: 'Get 10% off Photoshop.',
        badgeText: 'LIMITED TIME WEEKLY OFFER',
        price: 'US$383.88/yr',
        strikethroughPrice: 'US$32.99/mo',
        description: 'Create gorgeous images, rich graphics, and incredible art. Save 10% for the first year. Ends Mar 20.',
        link1Text: 'See terms',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@Merch-card (plans)',
      path: '/drafts/nala/blocks/merch-card/merch-cards-plans',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH5: 'Desktop',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        footerBlueButtonText: 'Buy now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@Merch-card (plans) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-plans-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Best value',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        footerBlueButtonText: 'Buy now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@Merch-card (plans, secure)',
      path: '/drafts/nala/blocks/merch-card/merch-card-plans-secure',
      data: {
        titleH3: 'Acrobat',
        titleH5: 'Desktop + Mobile',
        price: 'US$79.99/mo',
        description: 'The complete PDF solution for working anywhere (includes desktop, web, and mobile access).',
        link1Text: 'See plan & pricing details',
        checkboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
        secureLabel: /Secure transaction/i,
        footerBlueButton1Text: 'Buy now',
        footerBlueButton2Text: 'Buy now',
        footerOutlineButtonText: 'Free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '7',
      name: '@Merch-card (plans, secure) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-cards-plans-secure-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH5: 'Desktop',
        badgeText: 'Best value',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        checkboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
        secureLabel: /Secure transaction/i,
        footerBlueButton1Text: /Buy now/i,
        footerOutlineButtonText: 'Free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '8',
      name: '@Merch-card (catalog)',
      path: '/drafts/nala/blocks/merch-card/merch-cards-catalog',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '9',
      name: '@Merch-card (catalog) with badge',
      path: '/drafts/nala/blocks/merch-card/march-cards-catalog-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Most popular',
        badgeBgColor: '#EDCC2D',
        badgeColor: '#000000',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '10',
      name: '@Merch-card (catalog) with more info and badge',
      path: '/drafts/nala/blocks/merch-card/merch-cards-catalog-with-more-info-and-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Most popular',
        badgeBgColor: '#EDCC2D',
        badgeColor: '#000000',
        actionMenuListCount: 4,
        actionMenuText1: 'Best for',
        actionMenuText2: 'Storage',
        actionMenuText3: '100 GB of cloud storage',
        actionMenuText4: '100 GB of cloud storage',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '11',
      name: '@Merch-card (simplified-pricing-express)',
      path: '/fragments/be94c09d-67ef-43fb-973c-b825cc4a930f',
      data: {
        titleH2: 'Express - Create standout content',
        badgeText: 'LIMITED TIME OFFER',
        badgeBgColor: '#FFD700',
        badgeColor: '#000000',
        description: 'Make amazing social content, flyers, and more. Stand out with Adobe Express.',
        footerBlueButtonText: 'Start for free',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '12',
      name: '@Merch-card (simplified-pricing-express) with price',
      path: '/fragments/496a356c-3f8c-4941-874b-b99f31d115b7',
      data: {
        titleH2: 'Express Premium',
        badgeText: 'BEST VALUE',
        badgeBgColor: '#00C853',
        badgeColor: '#000000',
        price: 'US$9.99/mo',
        description: 'Unlock premium templates, fonts, and features. Create without limits.',
        footerBlueButtonText: 'Get Premium',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '13',
      name: '@Merch-card (simplified-pricing-express) with custom border',
      path: '/drafts/nala/blocks/merch-card/merch-card-simplified-pricing-express-border',
      data: {
        titleH2: 'Express with AI',
        badgeText: 'NEW',
        borderColor: '#E91E63',
        price: 'US$19.99/mo',
        strikethroughPrice: 'US$29.99/mo',
        description: 'Create content faster with AI-powered tools and generative features.',
        footerBlueButtonText: 'Try AI features',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '14',
      name: '@Merch-card (simplified-pricing-express) with multiple CTAs',
      path: '/drafts/nala/blocks/merch-card/merch-card-simplified-pricing-express-multi-cta',
      data: {
        titleH2: 'Express for teams',
        badgeText: 'EXCLUSIVE',
        badgeBgColor: '#1976D2',
        badgeColor: '#FFFFFF',
        price: 'US$14.99/mo',
        description: 'Collaborate on content creation with advanced sharing and brand controls.',
        footerOutlineButtonText: 'Learn more',
        footerBlueButtonText: 'Buy now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
  ],
};
