/* eslint-disable max-len */

module.exports = {
  FeatureName: 'Merch Card Block',
  features: [
    {
      tcid: '0',
      name: '@Merch-card (Segment)',
      path: '/drafts/nala/blocks/merch-card/merch-card-segment',
      data: {
        title: 'Individuals',
        price: 'US$59.99/mo',
        strikethroughPrice: 'US$89.99/mo',
        description: 'Save over 25% on 20+ apps, including Photoshop, Illustrator, and more. First year only. Ends 27',
        link1Text: 'See what\'s included',
        link2Text: 'Learn more',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@Merch-card (Segment) with Badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-segment-with-badge',
      data: {
        title: 'Individuals',
        badgeText: 'Best value',
        price: 'US$59.99/mo',
        strikethroughPrice: 'US$89.99/mo',
        description: 'Save over 25% on 20+ apps, including Photoshop, Illustrator, and more. First year only. Ends 27',
        link1Text: 'See what\'s included',
        link2Text: 'Learn more',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@Merch-card (special-offers) ',
      path: '/drafts/nala/blocks/merch-card/merch-card-special-offers',
      data: {
        titleH4: 'INDIVIDUALS',
        titleH3: 'Save over 30% on Creative Cloud All Apps.',
        description1: 'Get 20+ creative apps and save big when you choose a yearly plan instead of a monthly plan.',
        description2: 'Create gorgeous images, rich graphics, and incredible art. Save 10% for the first year. Ends Mar 20.',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@Merch-card (special-offers) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-special-offers-with-badge',
      data: {
        titleH4: 'INDIVIDUALS',
        titleH3: 'Get 10% off Photoshop.',
        badgeText: 'LIMITED TIME WEEKLY OFFER',
        price: 'US$383.88/yr',
        strikethroughPrice: 'US$32.99/mo',
        description: 'Create gorgeous images, rich graphics, and incredible art. Save 10% for the first year. Ends Mar 20.',
        link1Text: 'See terms',
        footerOutlineButtonText: 'Learn More',
        footerBlueButtonText: 'Save now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@Merch-card (plans)',
      path: '/drafts/nala/blocks/merch-card/merch-cards-plans',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH5: 'Desktop',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        footerBlueButtonText: 'Buy now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@Merch-card (plans) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-card-plans-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Best value',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        footerBlueButtonText: 'Buy now',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@Merch-card (plans, secure)',
      path: '/drafts/nala/blocks/merch-card/merch-card-plans-secure',
      data: {
        titleH3: 'Acrobat',
        titleH5: 'Desktop + Mobile',
        price: 'US$79.99/mo',
        description: 'The complete PDF solution for working anywhere (includes desktop, web, and mobile access).',
        link1Text: 'See plan & pricing details',
        checkboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
        secureLabel: /Secure transaction/i,
        footerBlueButton1Text: 'Buy now',
        footerBlueButton2Text: 'Buy now',
        footerOutlineButtonText: 'Free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '7',
      name: '@Merch-card (plans, secure) with badge',
      path: '/drafts/nala/blocks/merch-card/merch-cards-plans-secure-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH5: 'Desktop',
        badgeText: 'Best value',
        price: 'US$79.99/mo',
        description: 'Get 20+ Creative Cloud apps including Photoshop, Illustrator, Adobe Express, Premiere Pro, and Acrobat Pro. (Substance 3D apps are not included.)',
        link1Text: 'See plan & pricing details',
        checkboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
        secureLabel: /Secure transaction/i,
        footerBlueButton1Text: /Buy now/i,
        footerOutlineButtonText: 'Free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '8',
      name: '@Merch-card (catalog)',
      path: '/drafts/nala/blocks/merch-card/merch-cards-catalog',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '9',
      name: '@Merch-card (catalog) with badge',
      path: '/drafts/nala/blocks/merch-card/march-cards-catalog-with-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Most popular',
        badgeBgColor: '#EDCC2D',
        badgeColor: '#000000',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
    {
      tcid: '10',
      name: '@Merch-card (catalog) with more info and badge',
      path: '/drafts/nala/blocks/merch-card/merch-cards-catalog-with-more-info-and-badge',
      data: {
        titleH3: 'Creative Cloud All Apps',
        titleH4: 'Desktop',
        badgeText: 'Most popular',
        badgeBgColor: '#EDCC2D',
        badgeColor: '#000000',
        actionMenuListCount: 4,
        actionMenuText1: 'Best for',
        actionMenuText2: 'Storage',
        actionMenuText3: '100 GB of cloud storage',
        actionMenuText4: '100 GB of cloud storage',
        price: 'US$79.99/mo',
        description: 'Get 20+ creative apps including Photoshop, Illustrator, Premiere Pro, Acrobat Pro, and Adobe Express. (Substance 3D apps are not included.)',
        link1Text: 'See what’s included',
        link2Text: 'Learn more',
        footerBlueButton1Text: 'Buy now',
        footerOutlineButtonText: 'free trial',
      },
      tags: '@merch-card @smoke @regression @milo',
    },
  ],
};
