const taxonomy = {
  total: 10,
  offset: 0,
  limit: 10,
  data: [
    {
      Type: 'primaryProductName',
      Name: 'Experience Cloud',
      'Footer Promo Link': 'https://main--bacom--adobecom.hlx.page/footer-promo-experience',
      'Other Data': '17',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'primaryProductName',
      Name: 'Creative Cloud',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'primaryProductName',
      Name: 'Document Cloud',
      'Footer Promo Link': '',
      'Other Data': '54',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Insights & Inspiration',
      'Footer Promo Link': '',
      'Other Data': '90',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Insights & Inspiration | Creativity',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Insights & Inspiration | Creativity | 3D & AR',
      'Footer Promo Link': 'https://main--bacom--adobecom.hlx.page/footer-promo-3d-ar',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Marketing',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Marketing | Content Marketing',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Marketing | Email Marketing',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: '',
    },
    {
      Type: 'tag',
      Name: 'Marketing | Marketing Automation',
      'Footer Promo Link': '',
      'Other Data': '',
      ExcludeFromMetadata: 'X',
    },
  ],
  ':type': 'sheet',
};

export default taxonomy;
