module.exports = {
  '@gnav-signin': '.gnav-signin',
  '@gnav-profile-button': '.gnav-profile-button',
  '@gnav-signout': 'text=Sign Out',
  '@gnav-viewaccount': '.gnav-profile-header',
  '@gnav-manageTeam': 'text=Manage Team',
  '@email': '#EmailPage-EmailField',
  '@password': '#PasswordPage-PasswordField',
  '@email-continue-btn': '[data-id=EmailPage-ContinueButton]',
  '@verify-continue-btn': '[data-id=Page-PrimaryButton]',
  '@password-reset': 'text=Reset your password',
  '@password-continue-btn': '[data-id=PasswordPage-ContinueButton]',
  '@apple-signin': '[data-id=EmailPage-AppleSignInButton]',
  '@google-signin': '[data-id=EmailPage-GoogleSignInButton]',
  '@facebook-signin': '[data-id=EmailPage-FacebookSignInButton]',
  '@page-heading': '.spectrum-Heading1',
  '@gnav-ec-signin': '[daa-ll=Experience_Cloud-1]',
  '@gnav-comm-signin': '[daa-ll=Commerce__Magento-2]',
  '@gnav-multi-signin': '[daa-ll=Adobe_Account-5]',
  '@gnav-app-launcher': '.gnav-applications-button',
  '@cc-app-launcher': '#navmenu-apps >> ul >> li:nth-child(1) >> a',
  '@app-launcher-list': '.apps >> li',
};
