/* eslint-disable max-len */

module.exports = {
  FeatureName: 'Merch CCD Card Feature',
  features: [
    // SUGGESTED CARDS
    {
      tcid: '0',
      name: '@MAS-CCD-suggested-eyebrow',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '0a2ac7c9-1965-488e-beca-856849305313',
        title: 'Get the Photoshop plan',
        eyebrow: 'INDIVIDUALS',
        description: 'The full version of Photoshop plus Adobe Express Premium plan.',
        price: 'US$22.99/mo',
        cta: 'Buy now',
        osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@MAS-CCD-suggested-strikethrough',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '549f6981-f5c8-4512-b41c-313d60f375b2',
        title: 'Creative Cloud All Apps Plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save over 65% on Photoshop and more than 20 apps for the first year. Plus get the first month on us when purchase by Sep 2',
        price: 'US$19.99/mo',
        strikethroughPrice: 'US$59.99/mo',
        abmLabel: 'Annual, paid monthly',
        cta: 'Buy now',
        osi: 'Hnk2P6L5wYhnpZLFYTW5upuk2Y3AJXlso8VGWQ0l2TI',
        linkText: 'See terms',
        linkUrl: '',
        iconUrl: '',
        cardDaaLH: 'ccsn',
        linkAnalyticsId: 'see-terms',
        linkDaaLL: 'see-terms-1',
        ctaAnalyticsId: 'buy-now',
        ctaDaaLL: 'buy-now-2',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@MAS-CCD-suggested-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '8b198434-f32d-4a77-8be0-cd6b9f7155b1',
        title: 'Save 40% on Photoshop for teams and businesses',
        description: 'The full version of Photoshop, Adobe Express Premium plan, plus exclusive business features',
        price: 'US$37.99/mo',
        cta: 'Buy now',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@MAS-CCD-suggested-thin',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'cdfae8c5-4129-43bc-a283-9ce46d07e21f',
        title: 'Creative Cloud All Apps Plan',
        eyebrow: 'INDIVIDUALS',
        description: 'The full version of Photoshop plus Adobe Express Premium plan and more than 20 apps',
        price: 'US$59.99/mo',
        cta: 'Buy now',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@MAS-CCD-suggested-thin-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '33c8f437-3c39-48cc-8afd-938a13af5732',
        title: 'Save over 65% on your plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save over 65% on Photoshop and more than 20 apps for the first year. Plus get the first month on us until Sep 2',
        price: 'US$19.99/mo',
        cta: 'Buy now',
        linkText: 'See terms',
        linkUrl: '',
        iconUrl: '',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@MAS-CCD-suggested-thin-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '45783ec8-ed85-4595-a445-3f018ac4ad9d',
        title: 'Creative Cloud All Apps for teams',
        description: 'The full version of Photoshop plus Adobe Express Premium plan, more than 20 apps for design, video, and exclusive business features',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@MAS-CCD-suggested-wide-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '6217fb6d-e793-4235-af70-6f82401fc5de',
        title: 'Save over 65% on your plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save on Photoshop and more for the first year. Get the first month free when you purchase by Sep 2',
        price: 'US$19.99/mo',
        cta: 'Buy now',
        linkText: 'See terms',
        linkUrl: '',
        background: 'media_196e39eda2ba7ce0343ec138f3e3e41e5adcb787f.png',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '7',
      name: '@MAS-CCD-suggested-wide-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'd23182d8-fc92-483d-bcfe-d1fe3d3ce737',
        title: 'Creative Cloud All Apps for teams',
        description: 'The full version of Photoshop plus more than 20 apps for design, video, and exclusive business features.',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        background: 'media_196e39eda2ba7ce0343ec138f3e3e41e5adcb787f.png',
        iconUrl: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    // SLICE CARDS - SINGLE WIDTH
    {
      tcid: '8',
      name: '@MAS-CCD-slice-percentage',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '0ef2a804-e788-4959-abb8-b4d96a18b0ef',
        description: 'Save over 40% when you upgrade to Creative Cloud All apps',
        percentage: '40%',
        cta: 'Buy now',
        osi: 'PpnQ-UmW9NBwZwXlFw79zw2JybhvwIUwMTDYiIlu5qI',
        background: 'media-1508e7aec70760ac0ac13d9152f8030c1b67f70bf.png',
        // iconLink: '',
        cardDaaLH: 'ccsn',
        ctadDaaLL: 'buy-now-1',
        ctaAnalyticsId: 'buy-now',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    {
      tcid: '9',
      name: '@MAS-CCD-slice-mnemonics',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '58c7906f-70a6-4e2b-bc29-257ff2ade513',
        description: 'Creative Cloud Photography plan. Starting at',
        price: 'US$11.99/mo',
        cta: 'Buy now',
        background: 'media_10bef5ec21c22fd7fe201cb02735082df13bf4960.jpeg',
        iconLink1: 'https://www.adobe.com/products/photoshop.html',
        iconLink2: 'https://www.adobe.com/products/photoshop-lightroom.html',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    {
      tcid: '10',
      name: '@MAS-CCD-slice-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '51c23f28-504f-450d-9764-0e60f1e279b2',
        description: 'Save 25% on Photoshop. Starting at',
        linkText: 'See terms',
        linkUrl: '',
        price: 'US$22.99/mo',
        cta: 'Buy now',
        background: 'media_1526ec63ba66eead46d7bde733ac7c4e994d829f1.png',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    {
      tcid: '11',
      name: '@MAS-CCD-slice-percentage-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'c13897c7-de77-4e45-b23b-eec9fd66cad1',
        description: 'Save 40% when you upgrade your plan',
        percentage: '40%',
        linkText: 'See terms',
        linkUrl: '',
        cta: 'Buy now',
        background: 'media-1508e7aec70760ac0ac13d9152f8030c1b67f70bf.png',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    {
      tcid: '12',
      name: '@MAS-CCD-slice-without-mnemonic',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '2a293069-1f9a-45ae-9840-2fa0303fe685',
        description: 'Save on Creative Cloud with Mastercard',
        linkText: 'See terms',
        linkUrl: '',
        cta: 'Get offer',
        background: '2024-10-16-17-03-43.jpg',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    {
      tcid: '13',
      name: '@MAS-CCD-slice-badge',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '3d26df5b-0784-4967-8149-8a9e59131084',
        badge: 'Save 65%',
        description: 'Creative Cloud All Apps for teams. Starting at',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        background: 'media_158c1c22b1322dd28d7912d30fb27f29aa79f79b1.png',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
    // SLICE CARDS - WIDE (DOUBLE) WIDTH
    {
      tcid: '14',
      name: '@MAS-CCD-slice-wide-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'bdf40d06-5914-4f1f-aa10-77c5676fe671',
        description: 'Save over 30% on Creative Cloud All Apps. Register for MAX by August 31 and save US$200 on a full conference pass',
        linkText: 'See terms',
        linkUrl: '',
        cta: 'Register now',
        background: 'media_144906e76fce812811940ce88ceded4f8d12098b5.png',
        // iconLink: '',
        cardDaaLH: 'ccsn',
        linkAnalyticsId: 'see-terms',
        linkDaaLL: 'see-terms-1',
        ctaAnalyticsId: 'register-now',
        ctaDaaLL: 'register-now-2',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-wide @commerce @smoke @regression @milo',
    },
    {
      tcid: '15',
      name: '@MAS-CCD-slice-wide-badge',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '31205553-b453-4c9e-a2ef-7b6aa7bfdc72',
        badge: 'Huge savings*',
        description: 'Save 25% on Photoshop for the first six months.',
        linkText: 'See terms',
        linkUrl: '',
        cta: 'Buy now',
        osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
        background: 'media_10bef5ec21c22fd7fe201cb02735082df13bf4960.jpeg',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-wide @commerce @smoke @regression @milo',
    },
    {
      tcid: '16',
      name: '@MAS-CCD-slice-wide-price',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'f3e5f2e7-df41-4300-87b9-465b3ad11abc',
        description: 'Save 25% on Photoshop for the first six months',
        linkText: 'See terms',
        linkUrl: '',
        price: 'US$22.99/mo',
        cta: 'Buy now',
        background: 'media_10bef5ec21c22fd7fe201cb02735082df13bf4960.jpeg',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-wide @commerce @smoke @regression @milo',
    },
    {
      tcid: '17',
      name: '@MAS-CCD-slice-wide-strikethrough',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'c25b20cc-e8a3-4854-b94f-51eec7d0ec25',
        description: 'Creative cloud Photography plan.',
        linkText: 'See terms',
        linkUrl: '',
        price: 'US$19.99/mo',
        strikethroughPrice: 'US$22.99/mo',
        cta: 'Buy now',
        background: 'media_10bef5ec21c22fd7fe201cb02735082df13bf4960.jpeg',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-wide @commerce @smoke @regression @milo',
    },
    {
      tcid: '18',
      name: '@MAS-CCD-slice-wide-without-mnemonic',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '6b3c6c4e-e19f-4d08-914f-fcfd9f77ca14',
        description: 'Get industry-leading creative apps designed just for business. Creative Cloud All Apps for Teams. Starting at',
        linkText: 'See terms',
        linkUrl: '',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        background: 'media_158c1c22b1322dd28d7912d30fb27f29aa79f79b1.png',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-wide @commerce @smoke @regression @milo',
    },
    {
      tcid: '19',
      name: '@MAS-CCD-slice-upt-link',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '018bf7f7-1e82-4b16-9dd1-039ee013e490',
        linkText: 'See terms',
        offerid: '3B8086C370FDF28C8AEEE1C5BD233E5A',
        uptLinkUrl: 'https://www.adobe.com/offers/promo-terms.html?locale=en_US&country=US&offer_id=3B8086C370FDF28C8AEEE1C5BD233E5A&promotion_code=MHYXZS',
        // iconLink: '',
      },
      browserParams: '?theme=darkest',
      tags: '@mas-ccd @slice-card @slice-single @commerce @smoke @regression @milo',
    },
  ],
};
