/* eslint-disable max-len */

module.exports = {
  FeatureName: 'MAS Express Cards',
  features: [
    {
      tcid: '0',
      name: '@MAS-Express-Card-Free',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '67c78f03-7d88-44c9-9a06-05443ec9265d',
        title: 'Free',
        badge: 'For individuals',
        description: 'Basic content creation tools, limited generative AI credits and assets.',
        price: 'US$0.00',
        priceNote: 'Free to use. No credit card required.',
        cta: 'Get Adobe Express Free',
        variant: 'simplified-pricing-express',
      },
      tags: '@express @express-card @free @smoke @regression',
    },
    {
      tcid: '1',
      name: '@MAS-Express-Card-Premium',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: 'b28957b9-2341-40f9-9004-24446f68e5e5',
        title: 'Premium',
        badge: 'For individuals',
        description: 'Millions of premium templates and assets, more generative AI credits, and time saving features.',
        price: 'US$9.99',
        priceStrikethrough: true,
        priceNote: 'No annual commitment, billed monthly. Cancel anytime',
        cta: 'Start 30-day free trial',
        variant: 'simplified-pricing-express',
        gradientBorder: true,
      },
      tags: '@express @express-card @premium @smoke @regression',
    },
    {
      tcid: '2',
      name: '@MAS-Express-Card-Teams',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: 'aaa728dc-2b44-495c-b9f0-bb82044db18a',
        title: 'Teams',
        badge: 'For teams',
        description: 'Millions of premium templates and assets, more generative AI credits, and time saving features.',
        price: 'US$9.99',
        priceNote: 'Per month when billed annually with no annual commitment.',
        priceAdditionalNote: 'First year only. Min. two seats required. One-year commitment.',
        cta: 'Start 14-day free trial',
        variant: 'simplified-pricing-express',
        gradientBorder: true,
      },
      tags: '@express @express-card @teams @regression',
    },
    {
      tcid: '3',
      name: '@MAS-Express-Card-Enterprise',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: 'c847d523-9228-4793-bdab-f65fe2e80a56',
        title: 'Enterprise',
        badge: 'For organizations',
        description: 'Millions of premium templates and assets, more generative AI credits, and time saving features.',
        priceHeading: 'Contact sales',
        priceNote: 'Connect with sales to learn more about how Express can be used across your organization.',
        ctaLink: 'Request information',
        ctaUrl: 'https://adobe.com/express',
        variant: 'simplified-pricing-express',
        gradientBorder: true,
      },
      tags: '@express @express-card @enterprise @smoke @regression',
    },
  ],
};
