/* eslint-disable max-len */
const { DOCS_GALLERY_PATH, PRICE_PATTERN } = require('../../../libs/commerce.js');

module.exports = {
  FeatureName: 'MAS Express Cards',
  features: [
    // Simplified Pricing Express Cards
    {
      tcid: '0',
      name: '@MAS-Express-Card-Free',
      path: DOCS_GALLERY_PATH.EXPRESS,
      data: {
        id: '67c78f03-7d88-44c9-9a06-05443ec9265d',
        title: 'Free',
        badge: '', // No badge for free card
        description: 'Basic content creation tools, limited generative AI credits and assets.',
        price: /US\$0\.00/,
        priceNote: 'Free to use. No credit card required.',
        cta: 'Get Adobe Express Free',
        variant: 'simplified-pricing-express',
      },
      tags: '@express @express-card @free @simplified @commerce @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@MAS-Express-Card-Premium',
      path: DOCS_GALLERY_PATH.EXPRESS,
      data: {
        id: 'b28957b9-2341-40f9-9004-24446f68e5e5',
        title: 'Premium',
        badge: '', // No badge for premium card
        description: 'Access millions of assets, more AI credits, and premium tools.',
        price: PRICE_PATTERN.US.mo,
        priceNote: 'No annual commitment, billed monthly.',
        cta: 'Start 30-day free trial',
        variant: 'simplified-pricing-express',
        gradientBorder: false,
      },
      tags: '@express @express-card @premium @simplified @commerce @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@MAS-Express-Card-Firefly-Pro',
      path: DOCS_GALLERY_PATH.EXPRESS,
      data: {
        id: 'aaa728dc-2b44-495c-b9f0-bb82044db18a',
        title: 'Firefly Pro',
        badge: 'Best value',
        description: 'Get Adobe Express Premium plus 4,000 credits for creative AI and Adobe Photoshop on web and mobile for advanced image editing.',
        price: PRICE_PATTERN.US.mo,
        priceNote: 'No annual commitment, billed monthly.',
        priceAdditionalNote: '',
        cta: 'Start 14-day free trial',
        variant: 'simplified-pricing-express',
        gradientBorder: true,
      },
      tags: '@express @express-card @firefly-pro @simplified @commerce @smoke @regression @milo',
    },

    // Full Pricing Express Cards
    {
      tcid: '3',
      name: '@MAS-Full-Pricing-Express-Free',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '53fcf015-5c28-4214-bd2b-d4c22f1774b8',
        title: 'Adobe Express Free',
        badge: '',
        shortDescription: 'For students who want basic content creation tools, limited generative AI credits and assets.',
        description: 'Top features:',
        price: 'US$9.99/mo',
        priceNote: 'Free to use. No credit card required.',
        cta: 'Get free plan',
        variant: 'full-pricing-express',
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes basic editing tools and limited assets',
          featureList: [
            'Templates: Access to 100,000+ static and video templates',
            'Assets: 1M+ royalty-free photos, videos, music tracks, and design elements',
            'Fonts: Access to 1,000+ custom fonts',
            'Editing tools: Standard photo, video, and document editing tools',
            'Storage: 5GB',
            'Devices: Works on desktop browsers and mobile phones',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @free @commerce @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@MAS-Full-Pricing-Express-Premium',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '025dfceb-c035-45b7-8ea1-8feed25c8009',
        title: 'Adobe Express Premium',
        badge: '',
        hasMnemonic: true,
        shortDescription: 'For individuals who want millions of premium templates and assets, more generative AI credits, and time saving features.',
        description: 'Top features:',
        price: 'US$9.99/mo',
        priceNote: 'No annual commitment, billed monthly.',
        cta: 'Start 30-day free trial',
        variant: 'full-pricing-express',
        gradientBorder: false,
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes all Premium plan features, and more',
          featureList: [
            'Generative AI: 250 generative credits per month per user',
            'Templates: Access to all premium static and video templates',
            'Assets: 200M+ royalty-free photos, videos, music tracks, and design elements',
            'Fonts: Access to 25,000+ custom fonts',
            'Storage: 100GB',
            'One-click Resize: Automatically resize assets for multiple channels',
            'Brand management: Brand kits to maintain consistency across your content',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @premium @commerce @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@MAS-Full-Pricing-Express-Pro',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '9406f1ae-7bee-48c3-9892-49af6816033e',
        title: 'Express Free',
        badge: 'Best value',
        shortDescription: 'For individuals who want Adobe Express Premium plus 4,000 credits for creative AI and Adobe Photoshop on web and mobile for advanced image editing.',
        description: 'Top features:',
        price: 'US$9.99',
        priceNote: 'No annual commitment, billed monthly.',
        cta: 'Start 7-day free trial',
        variant: 'full-pricing-express',
        gradientBorder: true,
        borderColor: 'gradient-firefly-spectrum',
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes all Premium plan features, and more (except the 250 credits)',
          featureList: [
            'Generative AI for video and audio: 4,000 monthly generative credits',
            'Generative AI for images: Unlimited access to standard image features',
            'Text to Video: Generate up to 40 five-second videos',
            'Third-party models: Access partner generative AI models',
            'Translation: Translate up to 13 minutes of video and audio',
            'Sound effects: Generate up to 400 sound effects',
            'Advanced editing on web and mobile (full access): Powerful image editing',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @pro @commerce @smoke @regression @milo',
    },
  ],
};
