module.exports = {
  FeatureName: 'Brand Concierge block',
  features: [
    {
      tcid: '0',
      name: '@brand-concierge default',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge',
      tags: '@brand-concierge @smoke @regression @milo',
      data: {
        h2Text: 'Explore what you can do with Adobe apps.',
        bodyText: 'Choose an option or tell us what interests you',
        inputPlaceholder: 'Tell us about a project or idea that interests you',
        disclaimerText: 'By using this AI-powered automated chatbot',
      },
    },
    {
      tcid: '1',
      name: '@brand-concierge hero',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge-hero',
      tags: '@brand-concierge @brand-concierge-hero @smoke @regression @milo',
      data: {
        h2Text: 'Ask Adobe anything',
        inputPlaceholder: 'Ask anything',
        disclaimerText: 'By using this AI chatbot (beta), you agree Adobe may use your info',
      },
    },
    {
      tcid: '2',
      name: '@brand-concierge 404',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge-404',
      tags: '@brand-concierge @brand-concierge-404 @smoke @regression @milo',
      data: {
        h2Text: 'Sorry, we couldn\'t find that page.',
        inputPlaceholder: 'Tell us what you\'d like to create',
        disclaimerText: 'Use of this beta AI chatbot is subject to Adobe\'s Privacy Policy',
      },
    },
    {
      tcid: '3',
      name: '@brand-concierge floating button',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-button',
      tags: '@brand-concierge @brand-concierge-floating @regression @milo',
      data: {
        h2Text: 'Find the right app to bring your ideas to life.',
        inlinePromptCount: 4,
        inputPlaceholder: 'Ask a question',
        disclaimerText: 'Use of this beta AI chatbot is subject',
        floatingButtonText: 'Ask a question',
        welcomeHeading: 'Find the right app to bring your ideas to life.',
        minimumPromptCount: 4,
      },
    },
    {
      tcid: '4',
      name: '@brand-concierge floating button delay',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-button-delay',
      tags: '@brand-concierge @brand-concierge-floating-delay @regression @milo',
      data: {
        h2Text: 'Find the right app to bring your ideas to life.',
        inlinePromptCount: 4,
        inputPlaceholder: 'Ask a question',
        disclaimerText: 'Use of this beta AI chatbot is subject',
        floatingButtonText: 'Ask a question',
        welcomeHeading: 'Find the right app to bring your ideas to life.',
        minimumPromptCount: 4,
        delayClass: 'floating-delay-300',
      },
    },
    {
      tcid: '5',
      name: '@brand-concierge hero floating button',
      path: '/drafts/nala/blocks/brand-concierge/bc-hero-floating-button',
      tags: '@brand-concierge @brand-concierge-hero-floating @regression @milo',
      data: {
        h2Text: 'Ask Adobe anything',
        inputPlaceholder: 'Ask anything',
        inlinePromptCount: 4,
        disclaimerText: 'By using this AI chatbot (beta), you agree Adobe may use your info',
        floatingButtonText: 'Ask anything',
        minimumPromptCount: 4,
      },
    },
    {
      tcid: '6',
      name: '@brand-concierge floating button only',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-button-only',
      tags: '@brand-concierge @brand-concierge-floating-only @regression @milo',
      data: {
        floatingButtonText: 'Ask a question',
        welcomeHeading: 'Explore what you can do with Adobe apps.',
        minimumPromptCount: 4,
      },
    },
    {
      tcid: '7',
      name: '@brand-concierge floating anchor hide',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-anchor-hide',
      tags: '@brand-concierge @brand-concierge-anchor-hide @regression @milo',
      data: {
        floatingButtonText: 'Ask a question',
        welcomeHeading: 'Explore what you can do with Adobe apps.',
        minimumPromptCount: 4,
        delayClass: 'floating-delay-100',
      },
    },
    {
      tcid: '8',
      name: '@brand-concierge modal open close',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-button',
      tags: '@brand-concierge @brand-concierge-modal @regression @milo',
      data: {},
    },
    {
      tcid: '9',
      name: '@brand-concierge web client preload',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge',
      tags: '@brand-concierge @brand-concierge-preload @regression @milo',
      data: { scriptPattern: 'brand-concierge-web-agent/static-assets/main.js' },
    },
    {
      tcid: '10',
      name: '@brand-concierge webclient baseStage param',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge?webclient=baseStage',
      tags: '@brand-concierge @brand-concierge-webclient @regression @milo',
      data: {
        scriptPattern: 'experience-platform-brand-concierge-web-agent/static-assets/main.js',
        envPattern: 'experience-stage.adobe.net',
      },
    },
    {
      tcid: '11',
      name: '@brand-concierge hero floating aria-hidden',
      path: '/drafts/nala/blocks/brand-concierge/bc-hero-floating-button',
      tags: '@brand-concierge @brand-concierge-aria-hidden @regression @milo',
      data: {},
    },
    {
      tcid: '12',
      name: '@brand-concierge consent hide block',
      path: '/drafts/nala/blocks/brand-concierge/brand-concierge',
      tags: '@brand-concierge @brand-concierge-consent @regression @milo',
      data: {},
    },
    {
      // MWPW-194524 (PR #5940) - floating-anchor-delay<N> variant.
      // Hides the floating button when the page scroll is within N pixels of
      // the footer. Combined with floating-delay<M> to also hide near the top.
      tcid: '13',
      name: '@brand-concierge floating anchor delay',
      path: '/drafts/nala/blocks/brand-concierge/bc-floating-anchor-delay',
      tags: '@brand-concierge @brand-concierge-anchor-delay @regression @milo',
      data: {
        floatingButtonText: 'Ask a question',
        topDelayClass: 'floating-delay-100',
        anchorDelayClass: 'floating-anchor-delay-450',
        topDelayPx: 100,
        anchorDelayPx: 450,
      },
    },
  ],
};
