/* eslint-disable max-len */

module.exports = {
  FeatureName: 'Merch CCD Card Feature',
  features: [
    {
      tcid: '0',
      name: '@MAS-CCD-suggested-eyebrow',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '0a2ac7c9-1965-488e-beca-856849305313',
        title: 'Get the Photoshop plan',
        eyebrow: 'INDIVIDUALS',
        description: 'The full version of Photoshop plus Adobe Express Premium plan.',
        price: 'US$22.99/mo',
        cta: 'Buy now',
        offerid: '30404A88D89A328584307175B8B27616',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@MAS-CCD-suggested-strikethrough',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '549f6981-f5c8-4512-b41c-313d60f375b2',
        title: 'Creative Cloud All Apps Plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save over 65% on Photoshop and more than 20 apps for the first year. Plus get the first month on us when purchase by Sep 2',
        price: 'US$19.99/mo',
        strikethroughPrice: 'US$59.99/mo',
        cta: 'Buy now',
        offerid: '951DCCB08194F40B9C79951675547DF5',
        linkText: 'See terms',
        linkUrl: '',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@MAS-CCD-suggested-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '8b198434-f32d-4a77-8be0-cd6b9f7155b1',
        title: 'Save 40% on Photoshop for teams and businesses',
        description: 'The full version of Photoshop, Adobe Express Premium plan, plus exclusive business features',
        price: 'US$37.99/mo',
        cta: 'Buy now',
        offerid: 'D5349E66BACCC8C1B3C1EA63348ED949',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@MAS-CCD-suggested-thin',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'cdfae8c5-4129-43bc-a283-9ce46d07e21f',
        title: 'Creative Cloud All Apps Plan',
        eyebrow: 'INDIVIDUALS',
        description: 'The full version of Photoshop plus Adobe Express Premium plan and more than 20 apps',
        price: 'US$59.99/mo',
        cta: 'Buy now',
        offerid: '632B3ADD940A7FBB7864AA5AD19B8D28',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@MAS-CCD-suggested-thin-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '33c8f437-3c39-48cc-8afd-938a13af5732',
        title: 'Save over 65% on your plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save over 65% on Photoshop and more than 20 apps for the first year. Plus get the first month on us until Sep 2',
        price: 'US$19.99/mo',
        cta: 'Buy now',
        offerid: '951DCCB08194F40B9C79951675547DF5',
        linkText: 'See terms',
        linkUrl: '',
        iconUrl: '',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@MAS-CCD-suggested-thin-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '45783ec8-ed85-4595-a445-3f018ac4ad9d',
        title: 'Creative Cloud All Apps for teams',
        description: 'The full version of Photoshop plus Adobe Express Premium plan, more than 20 apps for design, video, and exclusive business features',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        offerid: '257E1D82082387D152029F93C1030624',
        background: 'media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@MAS-CCD-suggested-wide-seeterms',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: '6217fb6d-e793-4235-af70-6f82401fc5de',
        title: 'Save over 65% on your plan',
        eyebrow: 'STUDENTS AND TEACHERS',
        description: 'Save on Photoshop and more for the first year. Get the first month free when you purchase by Sep 2',
        price: 'US$19.99/mo',
        cta: 'Buy now',
        offerid: '951DCCB08194F40B9C79951675547DF5',
        linkText: 'See terms',
        linkUrl: '',
        background: 'media_196e39eda2ba7ce0343ec138f3e3e41e5adcb787f.png',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
    {
      tcid: '7',
      name: '@MAS-CCD-suggested-wide-noeyebrow-priceunit',
      path: '/libs/features/mas/docs/ccd.html',
      data: {
        id: 'd23182d8-fc92-483d-bcfe-d1fe3d3ce737',
        title: 'Creative Cloud All Apps for teams',
        description: 'The full version of Photoshop plus more than 20 apps for design, video, and exclusive business features.',
        price: 'US$89.99/mo',
        cta: 'Buy now',
        offerid: '257E1D82082387D152029F93C1030624',
        background: 'media_196e39eda2ba7ce0343ec138f3e3e41e5adcb787f.png',
        iconUrl: '',
      },
      browserParams: '?theme=dark',
      tags: '@mas-ccd @suggested-card @commerce @smoke @regression @milo',
    },
  ],
};
