module.exports = {
  name: 'Offer Selector Tool',
  features: [
    {
      tcid: '0',
      name: '@OST-Search-OfferID',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        productName: 'Photoshop',
        productNameShort: 'phsp',
        planType: 'PUF',
        offerType: 'TRIAL',
        price: 'US$263.88',
        opticalPrice: 'US$21.99',
        term: '/yr',
        opticalTerm: '/mo',
        unit: 'per license',
        taxLabel: 'excl. tax',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '1',
      name: '@OST-Offer-Entitlements',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        planType: 'PUF',
        offerType: 'TRIAL',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',

    },
    {
      tcid: '2',
      name: '@OST-Offer-Price',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        price: 'US$263.88',
        opticalPrice: 'US$21.99',
        term: '/yr',
        opticalTerm: '/mo',
        unit: 'per license',
        taxLabel: 'excl. tax',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '3',
      name: '@OST-Term',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        term: '/yr',
        opticalTerm: '/mo',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '4',
      name: '@OST-Unit',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        unit: 'per license',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '5',
      name: '@OST-TaxLabel',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        taxLabel: 'excl. tax',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '6',
      name: '@OST-TaxInclusivity',
      path: '/tools/ost',
      data: { offerID: '0ADF92A6C8514F2800BE9E87DB641D2A' },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '7',
      name: '@OST-Price-Promo',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        promo: 'testpromo',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '8',
      name: '@OST-Checkout-Link',
      path: '/tools/ost',
      data: {
        offerID: '0ADF92A6C8514F2800BE9E87DB641D2A',
        workflowStep_1: 'email',
        workflowStep_2: 'recommendation',
        promo: 'testpromo',
      },
      browserParams: '?token=',
      tags: '@ost @commerce @regression @nopr',
    },
    {
      tcid: '9',
      name: '@OST-OldPrice',
      path: '/tools/ost',
      data: { offerID: '0ADF92A6C8514F2800BE9E87DB641D2A' },
      browserParams: '?token=',
      tags: '@ost @commerce @f1 S@regression @nopr',
    },
  ],
};
