// module.exports = {
//   name: 'Promotions',
//   features: [
//     {
//       tcid: '0',
//       name: '@Promo-insert',
//       path: '/drafts/nala/features/promotions/promo-insert',
//       data: {
//         textMarquee: 'Promo test page',
//         textAfterMarquee: 'Marquee promo text insert',
//         textBeforeText: 'Text promo text insert',
//         textDefault: 'Default text',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '1',
//       name: '@Promo-replace',
//       path: '/drafts/nala/features/promotions/promo-replace',
//       data: {
//         textReplaceMarquee: 'Marquee promo replace',
//         textReplace: 'Promo text replace',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '2',
//       name: '@Promo-remove',
//       path: '/drafts/nala/features/promotions/promo-remove',
//       data: { textMarquee: 'Promo test page' },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '3',
//       name: '@Promo-two-manifests',
//       path: '/drafts/nala/features/promotions/promo-default',
//       data: {
//         textReplaceMarquee: 'Marquee promo replace',
//         textReplace: 'Promo text replace',
//         textAfterMarquee: 'Marquee promo text insert',
//         textBeforeText: 'Text promo text insert',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '4',
//       name: '@Promo-replace-fragment',
//       path: '/drafts/nala/features/promotions/promo-with-fragments',
//       data: { textReplaceMarquee: 'Marquee promo replace' },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '5',
//       name: '@Promo-future',
//       path: '/drafts/nala/features/promotions/promo-future',
//       data: {
//         mepPath: '/drafts/nala/features/promotions/manifests/promo-insert-future.json--all',
//         textMarquee: 'Promo test page',
//         textDefault: 'Default text',
//         textFuture: 'Future promo text insert',
//         status1: 'Scheduled', // new format
//         status2: 'inactive', // new format
//         manifestFile: 'promo-insert-future.json',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '6',
//       name: '@Promo-with-personalization',
//       path: '/drafts/nala/features/promotions/promo-with-personalization',
//       data: {
//         textMarquee: 'Promo test page',
//         textAfterMarquee: 'Marquee promo text insert',
//         textBeforeText: 'Text promo text insert',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '7',
//       name: '@Promo-with-personalization-and-target',
//       path: '/drafts/nala/features/promotions/promo-with-personalization-and-target',
//       data: {
//         textMarquee: 'Promo test page',
//         textAfterMarquee: 'Marquee promo text insert',
//         textBeforeText: 'Text promo text insert',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '8',
//       name: '@Promo-preview',
//       path: '/drafts/nala/features/promotions/promo-default',
//       data: {
//         mepInsertOn: '/drafts/nala/features/promotions/manifests/promo-insert.json--all',
//         mepReplaceOn: '/drafts/nala/features/promotions/manifests/promo-replace.json--all',
//         mepInsertOff: '/drafts/nala/features/promotions/manifests/promo-insert.json--default',
//         mepReplaceOff: '/drafts/nala/features/promotions/manifests/promo-replace.json--default',
//         textMarquee: 'Promo test page',
//         textDefault: 'Default text',
//         textAfterMarquee: 'Marquee promo text insert',
//         textBeforeText: 'Text promo text insert',
//         textReplaceMarquee: 'Marquee promo replace',
//         textReplace: 'Promo text replace',
//         inactiveStatus: 'inactive',
//         manifestInsertFile: 'promo-insert.json',
//         manifestReplaceFile: 'promo-replace.json',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '9',
//       name: '@Promo-page-filter-insert',
//       path: '/drafts/nala/features/promotions/promo-page-filter-insert',
//       data: {
//         textMarquee: 'Promo test page',
//         textDefault: 'Default text',
//         textAfterMarquee: 'Marquee promo text insert',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '10',
//       name: '@Promo-page-filter-replace',
//       path: '/drafts/nala/features/promotions/promo-page-filter-replace',
//       data: {
//         textReplaceMarquee: 'Marquee promo replace',
//         textDefault: 'Default text',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '11',
//       name: '@Promo-page-filter-geo',
//       path: '/drafts/nala/features/promotions/promo-page-filter',
//       data: {
//         textMarquee: 'Promo test page',
//         textDefault: 'Default text',
//         textBeforeText: 'Common Promo',
//         CO_DE: '/de',
//         textBeforeTextDE: 'German Promo',
//         CO_FR: '/fr',
//         textBeforeTextFR: 'French Promo',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '12',
//       name: '@Promo-remove-fragment',
//       path: '/drafts/nala/features/promotions/promo-with-fragments-remove',
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '13',
//       name: '@Promo-fragment-insert',
//       path: '/drafts/nala/features/promotions/promo-with-fragments-insert',
//       data: {
//         textMarquee: 'Fragment marquee',
//         textBeforeMarquee: 'Text promo text insert',
//         textAfterMarquee: 'Marquee promo text insert',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '14',
//       name: '@Promo-mas-replace-card-in-collection',
//       path: '/drafts/nala/features/commerce/plans?mep=/drafts/nala/features/promotions/manifests/promo-replace-card-in-collection.json',
//       data: {
//         collectionId: 'cffc325f-3405-4619-8892-75c303a37966',
//         baseCardId: '7819acb2-fb23-46c5-ab7f-f59b2e29ee1e',
//         promoCardId: 'eccb6135-55ea-490f-889a-a7a7f324f347',
//         overrideAttributes: '7819acb2-fb23-46c5-ab7f-f59b2e29ee1e:eccb6135-55ea-490f-889a-a7a7f324f347',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '15',
//       name: '@Promo-mas-replace-collection-with-collection',
//       path: '/drafts/nala/features/commerce/plans?mep=/drafts/nala/features/promotions/manifests/promo-replace-collection-with-collection.json',
//       data: {
//         baseCollectionId: 'cffc325f-3405-4619-8892-75c303a37966',
//         promoCollectionId: '3d48f7cb-5285-46a9-a1cc-a242b8a39db8',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '16',
//       name: '@Promo-mas-replace-collection-with-fragment',
//       path: '/drafts/nala/features/commerce/plans?mep=/drafts/nala/features/promotions/manifests/promo-replace-collection-with-fragment.json',
//       data: {
//         collectionId: 'cffc325f-3405-4619-8892-75c303a37966',
//         fragmentPath: '/drafts/nala/features/promotions/fragments/mas-collection-replacement-frag',
//       },
//       tags: '@promo @commerce @smoke @regression @milo',
//     },
//   ],
// };
