import { createTag } from '../../../utils/utils.js';
import { decorateViewportContent } from '../../../utils/decorate.js';

// GENERATED by M10 generate-v2.mjs from Figma "Audience - Resting" (9848:39806).
// Authored block shape (rows):
//   [heading]                       -> section title
//   [eyebrow | media | tagline] x 4  -> routing cards. Order-independent:
//                                        the media cell is the one with a <picture>,
//                                        the rest are text slots placed by CSS order.
//   [image image ...]               -> logo strip

const CLASS = 'audience-router';

function decorate(block) {
  const rows = [...block.children];
  if (rows.length < 6) return;

  const headingRow = rows.shift();
  const stripRow = rows.pop();

  headingRow.classList.add(`${CLASS}-heading`);

  const cards = rows.map((row) => {
    const cells = [...row.children];
    // semantic, content-based (NOT positional): the media cell is the one with a
    // picture; the remaining cells are the text slots, in authored order. Their
    // VISUAL order is set by CSS 'order' from the design, so an author never has
    // to know whether the label sits above or below the image.
    const mediaCell = cells.find((c) => c.querySelector('picture, img')) || cells[0];
    const textCells = cells.filter((c) => c !== mediaCell);

    mediaCell.classList.add(`${CLASS}-card-media`);

    const [eyebrowCell, taglineCell] = textCells;
    eyebrowCell?.classList.add(`${CLASS}-card-eyebrow-slot`);
    taglineCell?.classList.add(`${CLASS}-card-tagline-slot`);
    eyebrowCell?.querySelector('p')?.classList.add(`${CLASS}-card-eyebrow`);
    taglineCell?.querySelector('p')?.classList.add(`${CLASS}-card-tagline`);

    const card = createTag('div', { class: `${CLASS}-card` });
    card.append(...cells);
    return card;
  });

  const row = createTag('div', { class: `${CLASS}-row` }, cards);

  // the strip is full-bleed: an outer clip box escapes to the viewport, an inner
  // track carries the (deliberately wider-than-viewport) artwork.
  stripRow.classList.add(`${CLASS}-strip`);
  const track = createTag('div', { class: `${CLASS}-strip-track` }, [...stripRow.children]);
  stripRow.replaceChildren(track);

  const bleed = createTag('div', { class: `${CLASS}-bleed` }, [row, stripRow]);

  block.replaceChildren(headingRow, bleed);
}

export default function init(el) {
  el.classList.add(CLASS);
  decorateViewportContent(el, decorate);
}
