module.exports = {
  BlockName: 'Carousel A11Y Enhancement Tests',
  features: [
    {
      tcid: 'a11y-01',
      name: '@Carousel A11Y - Keyboard Navigation',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @keyboard @smoke @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-02',
      name: '@Carousel A11Y - Focus Management',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @focus @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-03',
      name: '@Carousel A11Y - Lightbox Modal',
      path: '/drafts/nala/blocks/carousel/fullpage-carousel',
      tags: '@carousel @a11y @lightbox @modal @smoke @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-04',
      name: '@Carousel A11Y - ARIA Live Regions',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @aria @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-05',
      name: '@Carousel A11Y - ARIA Attributes',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @aria @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-06',
      name: '@Carousel A11Y - Button Semantics',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @semantic @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-07',
      name: '@Carousel A11Y - Axe Core Scans',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @axe @smoke @regression @milo',
      envs: '@milo-live @milo-prod',
    },
    {
      tcid: 'a11y-08',
      name: '@Carousel A11Y - Edge Cases',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @a11y @edge @regression @milo',
      envs: '@milo-live @milo-prod',
    },
  ],
};
