module.exports = {
  FeatureName: 'Chart Block',
  features: [
    {
      tcid: '0',
      name: '@Chart (area, green, border)',
      path: '/drafts/nala/blocks/chart/chart-area-green-border',
      data: {
        chartType: 'area green border',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@Chart (bar, border)',
      path: '/drafts/nala/blocks/chart/chart-bar-border',
      data: {
        chartType: 'bar border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@Chart (column, border)',
      path: '/drafts/nala/blocks/chart/chart-column-border',
      data: {
        chartType: 'column border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '3',
      name: '@Chart (donut, border)',
      path: '/drafts/nala/blocks/chart/chart-donut-border',
      data: {
        chartType: 'donut border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '4',
      name: '@Chart (line, border)',
      path: '/drafts/nala/blocks/chart/chart-line-border',
      data: {
        chartType: 'line border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '5',
      name: '@Chart (oversized-number, border)',
      path: '/drafts/nala/blocks/chart/chart-oversized-number-border',
      data: {
        chartType: 'oversized-number border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        circleNumber: '25',
        circleSubTitle: 'Out of 60 days',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
    {
      tcid: '6',
      name: '@Chart (pie, border)',
      path: '/drafts/nala/blocks/chart/chart-pie-border',
      data: {
        chartType: 'pie border large',
        titleH3: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        subTitle: 'Revenue dollars: 2020 vs 2021 forecasted vs 2021 actuals.',
        footNote: 'Footnote lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      },
      tags: '@chart @smoke @regression @milo',
    },
  ],
};
