/* eslint-disable max-len */

module.exports = {
  FeatureName: 'MAS Full Pricing Express Cards',
  features: [
    {
      tcid: '0',
      name: '@MAS-Full-Pricing-Express-Free',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '53fcf015-5c28-4214-bd2b-d4c22f1774b8',
        title: 'Adobe Express Free',
        badge: '', // No badge for free card
        shortDescription: 'For students who want basic content creation tools, limited generative AI credits and assets.',
        description: 'Top features:',
        price: 'US$9.99/mo',
        priceNote: 'Free to use. No credit card required.',
        cta: 'Get free plan',
        variant: 'full-pricing-express',
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes basic editing tools and limited assets',
          featureList: [
            'Templates: Access to 100,000+ static and video templates',
            'Assets: 1M+ royalty-free photos, videos, music tracks, and design elements',
            'Fonts: Access to 1,000+ custom fonts',
            'Editing tools: Standard photo, video, and document editing tools',
            'Storage: 5GB',
            'Devices: Works on desktop browsers and mobile phones',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @free @commerce @smoke @regression @milo',
    },
    {
      tcid: '1',
      name: '@MAS-Full-Pricing-Express-Premium',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '025dfceb-c035-45b7-8ea1-8feed25c8009',
        title: 'Adobe Express Premium',
        badge: '', // No badge for premium card
        hasMnemonic: true,
        shortDescription: 'For individuals who want millions of premium templates and assets, more generative AI credits, and time saving features.',
        description: 'Top features:',
        price: 'US$9.99/mo',
        priceNote: 'No annual commitment, billed monthly.',
        cta: 'Start 30-day free trial',
        variant: 'full-pricing-express',
        gradientBorder: false,
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes all Premium plan features, and more',
          featureList: [
            'Generative AI: 250 generative credits per month per user',
            'Templates: Access to all premium static and video templates',
            'Assets: 200M+ royalty-free photos, videos, music tracks, and design elements',
            'Fonts: Access to 25,000+ custom fonts',
            'Storage: 100GB',
            'One-click Resize: Automatically resize assets for multiple channels',
            'Brand management: Brand kits to maintain consistency across your content',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @premium @commerce @smoke @regression @milo',
    },
    {
      tcid: '2',
      name: '@MAS-Full-Pricing-Express-Pro',
      path: '/libs/features/mas/docs/express.html',
      data: {
        id: '9406f1ae-7bee-48c3-9892-49af6816033e',
        title: 'Adobe Firefly Pro',
        badge: 'Best value',
        shortDescription: 'For individuals who want Adobe Express Premium plus 4,000 credits for creative AI and Adobe Photoshop on web and mobile for advanced image editing.',
        description: 'Top features:',
        price: 'US$9.99',
        priceNote: 'No annual commitment, billed monthly.',
        cta: 'Start 7-day free trial',
        variant: 'full-pricing-express',
        gradientBorder: true,
        borderColor: 'gradient-firefly-spectrum',
        features: {
          topFeatures: 'Top features:',
          includesText: 'Includes all Premium plan features, and more (except the 250 credits)',
          featureList: [
            'Generative AI for video and audio: 4,000 monthly generative credits',
            'Generative AI for images: Unlimited access to standard image features',
            'Text to Video: Generate up to 40 five-second videos',
            'Third-party models: Access partner generative AI models',
            'Translation: Translate up to 13 minutes of video and audio',
            'Sound effects: Generate up to 400 sound effects',
            'Advanced editing on web and mobile (full access): Powerful image editing',
          ],
        },
        compareLink: 'Compare all features',
      },
      tags: '@full-pricing-express @express-card @pro @commerce @smoke @regression @milo',
    },
  ],
};
