/* eslint-disable max-len */

const { PRICE_PATTERN, PLANS_NALA_PATH } = require('../../../../libs/commerce.js');

module.exports = {
  FeatureName: 'Merch Plans Cards Feature',
  features: [
    // PLANS CARDS
    {
      tcid: '0',
      name: '@MAS-Plans-Load',
      path: PLANS_NALA_PATH.US,
      data: {
        cards: [
          {
            id: '146fec18-3d9c-4f93-908b-fd5e4ee76436',
            title: 'Creative Cloud Pro',
            description: 'Get 20+ apps, including Photoshop, Illustrator, Premiere Pro, and Acrobat Pro, plus Adobe Firefly standard and premium creative AI features for images, video, and audio.',
            price: PRICE_PATTERN.US.mo,
            abmLabel: 'Annual, billed monthly',
            cta: 'Select',
            osi: 'r_JXAnlFI7xD6FxWKl2ODvZriLYBoSL701Kd1hRyhe8',
            linkText: 'See all plans & pricing details',
            linkAnalyticsId: 'see-all-plans-and-pricing',
            linkDaaLL: 'see-all-plans-and-pricing-1--ccsn--card',
            linkAriaLabel: 'See all plans & pricing details - Creative Cloud All Apps - Individuals',
            ctaAnalyticsId: 'select',
            ctaDaaLL: 'select-2--ccsn--card',
            ctaAriaLabel: 'Select - Creative Cloud All Apps - Individuals',
            checkoutParams: {
              co: 'US',
              ctx: 'if',
              lang: 'en',
              cli: 'creative',
              ms: 'COM',
              ot: 'BASE',
              cs: 'INDIVIDUAL',
              pa: 'ccsn_direct_individual',
              ao: 'stks_direct_individual',
              rtc: 't',
              lo: 'sl',
              af: 'uc_new_user_iframe,uc_new_system_close',
            },
          },
          {
            id: '10db2ced-e32e-477d-9ae7-7f61cf9b4216',
            title: 'Photography',
            description: 'Lightroom, Lightroom Classic, Photoshop on desktop, web, iPhone, and iPad, and 1TB of cloud storage.',
            price: PRICE_PATTERN.US.mo,
            abmLabel: 'Annual, billed monthly',
            cta: 'Select',
            osi: 'MzCpF9nUi8rEzyW-9slEUwtRenS69PRW5fp84a93uK4',
            linkText: 'See all plans & pricing details',
            linkAnalyticsId: 'see-all-plans-and-pricing',
            linkDaaLL: 'see-all-plans-and-pricing-1--ples--card',
            linkAriaLabel: 'See all plans & pricing details - PLES - Individuals',
            ctaAnalyticsId: 'select',
            ctaDaaLL: 'select-2--ples--card',
            ctaAriaLabel: 'Select - PLES - Individuals',
            checkoutParams: {
              co: 'US',
              ctx: 'if',
              lang: 'en',
              cli: 'creative',
              ms: 'COM',
              ot: 'BASE',
              cs: 'INDIVIDUAL',
              pa: 'PA-128',
              rtc: 't',
              lo: 'sl',
              af: 'uc_new_user_iframe,uc_new_system_close',
            },

          },
        ],
      },
      tags: '@mas-acom @mas-plans-card @commerce @smoke @regression @milo @plans-load',
    },
    {
      tcid: '1',
      name: '@MAS-Plans-Category',
      path: PLANS_NALA_PATH.US,
      data: {
        categories: {
          all: {
            products: [
              'Creative Cloud Pro',
              'Photography',
              'Acrobat Pro',
              'Photoshop',
              'Adobe Premiere Pro',
              'Illustrator',
              'After Effects',
              'Adobe Express',
              'Adobe Firefly Standard',
              'Adobe Firefly Pro',
              'Adobe Firefly Premium',
              'InDesign',
              'Lightroom',
              'Acrobat Studio',
              'AI Assistant for Acrobat',
              'Audition',
              'Animate',
              'Adobe Substance 3D Collection',
              'Adobe Substance 3D Texturing',
              'Dreamweaver',
              'InCopy',
              'Creative Cloud Standard',
              'Acrobat Standard',
              'Adobe Stock',
            ],
            count: 24,
          },
          photo: {
            products: [
              'Creative Cloud Pro',
              'Photography',
              'Photoshop',
              'Lightroom',
              'Adobe Firefly Standard',
              'Adobe Firefly Pro',
              'Adobe Firefly Premium',
              'Adobe Stock',
            ],
            count: 8,
            browserFilter: '#filter=photography',
          },
          'graphic-design': {
            products: [
              'Creative Cloud Pro',
              'Photoshop',
              'Illustrator',
              'Adobe Express',
              'Adobe Firefly Standard',
              'Adobe Firefly Pro',
              'Adobe Firefly Premium',
              'InDesign',
              'InCopy',
              'Acrobat Pro',
              'Adobe Stock',
            ],
            count: 11,
            browserFilter: '#filter=design',
          },
          video: {
            products: [
              'Creative Cloud Pro',
              'Adobe Premiere Pro',
              'After Effects',
              'Adobe Firefly Standard',
              'Adobe Firefly Pro',
              'Adobe Firefly Premium',
              'Adobe Express',
              'Audition',
              'Animate',
              'Adobe Stock',
            ],
            count: 10,
            browserFilter: '#filter=video-audio',
          },
          illustration: {
            products: [
              'Creative Cloud Pro',
              'Photoshop',
              'Illustrator',
              'Adobe Firefly Standard',
              'Adobe Firefly Pro',
              'Adobe Firefly Premium',
              'Adobe Stock',
            ],
            count: 7,
            browserFilter: '#filter=illustration',
          },
          'acrobat-pdf': {
            products: [
              'Creative Cloud Pro',
              'Acrobat Pro',
              'AI Assistant for Acrobat',
              'Acrobat Standard',
            ],
            count: 4,
            browserFilter: '#filter=acrobat',
          },
          '3d-ar': {
            products: [
              'Adobe Substance 3D Collection',
              'Adobe Substance 3D Texturing',
            ],
            count: 2,
            browserFilter: '#filter=3dar',
          },
          'social-media': {
            products: [
              'Adobe Express',
              'Adobe Premiere Pro',
              'Lightroom',
            ],
            count: 3,
            browserFilter: '#filter=social',
          },
        },
      },
      tags: '@mas-acom @mas-plans-card @commerce @smoke @regression @milo @plans-category-switching',
    },
    {
      tcid: '2',
      name: '@MAS-Plans-Tabs-Deeplink',
      path: PLANS_NALA_PATH.US,
      browserParams: {
        edu: '?plan=edu',
        team: '?plan=team',
        edu_inst: '?plan=edu_inst',
        individual: '?plan=individual',
      },
      tags: '@mas-acom @mas-plans-card @commerce @smoke @regression @milo @plans-tabs-deeplink',
    },
    {
      tcid: '3',
      name: '@MAS-Plans-Modal-Deeplink',
      path: PLANS_NALA_PATH.US,
      browserParams: '#miniplans-buy-all-apps',
      tags: '@mas-acom @mas-plans-card @commerce @smoke @regression @milo @plans-modal-deeplink',
    },
  ],
};
