// /* eslint-disable max-len */

// const { PRICE_PATTERN, PLANS_NALA_PATH } = require('../../../../libs/commerce.js');

// module.exports = {
//   FeatureName: 'Merch Plans Cards Feature',
//   features: [
//     // PLANS CARDS
//     {
//       tcid: '0',
//       name: '@MAS-Plans-Load',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cards: [
//           {
//             id: '146fec18-3d9c-4f93-908b-fd5e4ee76436',
//             badge: 'Best value',
//             title: 'Creative Cloud Pro',
//             description: 'Get 20+ apps, including Photoshop, Illustrator, Premiere Pro, and Acrobat Pro, plus Adobe Firefly standard and premium creative AI features for images, video, and audio.',
//             price: PRICE_PATTERN.US.mo,
//             abmLabel: 'Annual, billed monthly',
//             cta: 'Select',
//             osi: 'r_JXAnlFI7xD6FxWKl2ODvZriLYBoSL701Kd1hRyhe8',
//             linkText: 'See all plans & pricing details',
//             linkAnalyticsId: 'see-all-plans-and-pricing',
//             linkDaaLL: 'see-all-plans-and-pricing-1--ccsn--card',
//             linkAriaLabel: 'See all plans & pricing details - Creative Cloud All Apps - Individuals',
//             stockCheckboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
//             ctaAnalyticsId: 'select',
//             ctaDaaLL: 'select-2--ccsn--card',
//             ctaAriaLabel: 'Select - Creative Cloud All Apps - Individuals',
//             checkoutParams: {
//               co: 'US',
//               ctx: 'if',
//               lang: 'en',
//               cli: 'creative',
//               ms: 'COM',
//               ot: 'BASE',
//               cs: 'INDIVIDUAL',
//               pa: 'ccsn_direct_individual',
//               rtc: 't',
//               lo: 'sl',
//               af: 'uc_new_user_iframe,uc_new_system_close',
//             },
//           },
//           {
//             id: '10db2ced-e32e-477d-9ae7-7f61cf9b4216',
//             title: 'Photography',
//             description: 'Lightroom, Lightroom Classic, Photoshop on desktop, web, iPhone, and iPad, and 1TB of cloud storage.',
//             price: PRICE_PATTERN.US.mo,
//             abmLabel: 'Annual, billed monthly',
//             cta: 'Select',
//             osi: 'MzCpF9nUi8rEzyW-9slEUwtRenS69PRW5fp84a93uK4',
//             linkText: 'See all plans & pricing details',
//             linkAnalyticsId: 'see-all-plans-and-pricing',
//             linkDaaLL: 'see-all-plans-and-pricing-1--ples--card',
//             linkAriaLabel: 'See all plans & pricing details - PLES - Individuals',
//             stockCheckboxLabel: 'Add a 30-day free trial of Adobe Stock.*',
//             ctaAnalyticsId: 'select',
//             ctaDaaLL: 'select-2--ples--card',
//             ctaAriaLabel: 'Select - PLES - Individuals',
//             checkoutParams: {
//               co: 'US',
//               ctx: 'if',
//               lang: 'en',
//               cli: 'creative',
//               ms: 'COM',
//               ot: 'BASE',
//               cs: 'INDIVIDUAL',
//               pa: 'PA-128',
//               rtc: 't',
//               lo: 'sl',
//               af: 'uc_new_user_iframe,uc_new_system_close',
//             },

//           },
//         ],
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '1',
//       name: '@MAS-Plans-Category',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         categories: {
//           all: {
//             products: [
//               'Creative Cloud Pro',
//               'Photography',
//               'Acrobat Pro',
//               'Photoshop',
//               'Adobe Premiere Pro',
//               'Illustrator',
//               'After Effects',
//               'Adobe Express',
//               'Adobe Firefly Standard',
//               'Adobe Firefly Pro',
//               'Adobe Firefly Premium',
//               'InDesign',
//               'Lightroom',
//               'Acrobat Studio',
//               'AI Assistant for Acrobat',
//               'Audition',
//               'Animate',
//               'Adobe Substance 3D Collection',
//               'Adobe Substance 3D Texturing',
//               'Dreamweaver',
//               'InCopy',
//               'Creative Cloud Standard',
//               'Acrobat Standard',
//               'Adobe Stock',
//             ],
//             count: 24,
//           },
//           Photo: {
//             products: [
//               'Creative Cloud Pro',
//               'Photography',
//               'Photoshop',
//               'Lightroom',
//               'Adobe Firefly Standard',
//               'Adobe Firefly Pro',
//               'Adobe Firefly Premium',
//               'Adobe Stock',
//             ],
//             count: 8,
//             browserFilter: '#filter=photography',
//             sidenavValue: 'photography',
//             daaLh: 'photography--cat',
//           },
//           'Graphic Design': {
//             products: [
//               'Creative Cloud Pro',
//               'Photoshop',
//               'Illustrator',
//               'Adobe Express',
//               'Adobe Firefly Standard',
//               'Adobe Firefly Pro',
//               'Adobe Firefly Premium',
//               'InDesign',
//               'InCopy',
//               'Acrobat Pro',
//               'Adobe Stock',
//             ],
//             count: 11,
//             browserFilter: '#filter=design',
//             sidenavValue: 'design',
//             daaLh: 'design--cat',
//           },
//           Video: {
//             products: [
//               'Creative Cloud Pro',
//               'Adobe Premiere Pro',
//               'After Effects',
//               'Adobe Firefly Standard',
//               'Adobe Firefly Pro',
//               'Adobe Firefly Premium',
//               'Adobe Express',
//               'Audition',
//               'Animate',
//               'Adobe Stock',
//             ],
//             count: 10,
//             browserFilter: '#filter=video-audio',
//             sidenavValue: 'video-audio',
//             daaLh: 'video-audio--cat',
//           },
//           Illustration: {
//             products: [
//               'Creative Cloud Pro',
//               'Photoshop',
//               'Illustrator',
//               'Adobe Firefly Standard',
//               'Adobe Firefly Pro',
//               'Adobe Firefly Premium',
//               'Adobe Stock',
//             ],
//             count: 7,
//             browserFilter: '#filter=illustration',
//             sidenavValue: 'illustration',
//             daaLh: 'illustration--cat',
//           },
//           'Acrobat and PDF': {
//             products: [
//               'Creative Cloud Pro',
//               'Acrobat Pro',
//               'AI Assistant for Acrobat',
//               'Acrobat Standard',
//             ],
//             count: 4,
//             browserFilter: '#filter=acrobat',
//             sidenavValue: 'acrobat',
//             daaLh: 'acrobat--cat',
//           },
//           '3D and AR': {
//             products: [
//               'Adobe Substance 3D Collection',
//               'Adobe Substance 3D Texturing',
//             ],
//             count: 2,
//             browserFilter: '#filter=3dar',
//             sidenavValue: '3dar',
//             daaLh: '3dar--cat',
//           },
//           'Social Media': {
//             products: [
//               'Adobe Express',
//               'Adobe Premiere Pro',
//               'Lightroom',
//             ],
//             count: 3,
//             browserFilter: '#filter=social',
//             sidenavValue: 'social',
//             daaLh: 'social--cat',
//           },
//         },
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '2',
//       name: '@MAS-Plans-Tabs-Deeplink',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         tabs: {
//           Education: {
//             tabId: 'edu',
//             urlParam: '?plan=edu',
//           },
//           Business: {
//             tabId: 'team',
//             urlParam: '?plan=team',
//           },
//           'Schools & Universities': {
//             tabId: 'edu_inst',
//             urlParam: '?plan=edu_inst',
//           },
//           Individual: {
//             tabId: 'individual',
//             urlParam: '?plan=individual',
//           },
//         },
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '3',
//       name: '@MAS-Plans-Modal-Deeplink',
//       path: PLANS_NALA_PATH.US,
//       browserParams: '#miniplans-buy-all-apps',
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '4',
//       name: '@MAS-Plans-Single-App-Deeplink',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cardid: '75019c6c-ca13-4b14-b665-c44f0188638b',
//         filter: 'Illustration',
//         selectedValue: 'illustration',
//       },
//       browserParams: {
//         landing: '?single_app=illustrator',
//         expected: '#filter=illustration&single_app=illustrator',
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '5',
//       name: '@MAS-Plans-Filter-Hash',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         filter: 'Photo',
//         selectedValue: 'photography',
//       },
//       browserParams: {
//         landing: '?filter=photography',
//         expected: '#filter=photography',
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '6',
//       name: '@MAS-Plans-Buynow-Modal-Stock',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cardid: '41f417d4-34ad-4b3e-828f-ab42fe782e27',
//         stockOSI: 'CCR5FPiUwE6AfLMkubkLibOiapCnMlqqnbUWIPXVuvQ',
//         stockCheckoutParam: 'ao=stks_direct_individual',
//       },
//       browserParams: '?plan=edu',
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '7',
//       name: '@MAS-Plans-See-All-Plans-Modal-Stock',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cardid: '146fec18-3d9c-4f93-908b-fd5e4ee76436',
//         stockOSI: 'JWIwpOv5nOckxDEBJeQWHa8spk7iEo4EEnQNQ1_YbmE',
//         stockCheckoutParam: 'ao=stks_direct_individual',
//       },
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '8',
//       name: '@MAS-Plans-Quantity-Selector',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cardid: '676ce087-a941-4a50-adae-97601e5a448b',
//         quantity: '3',
//       },
//       browserParams: '?plan=team',
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//     {
//       tcid: '9',
//       name: '@MAS-Plans-literals-override',
//       path: PLANS_NALA_PATH.US,
//       data: {
//         cardid: '0a12998f-01d6-4ff2-a71e-3fd48999f6b8',
//         unitText: 'per user',
//       },
//       browserParams: '?plan=edu_inst',
//       tags: '@mas-acom @mas-plans-page @commerce @smoke @regression @milo',
//     },
//   ],
// };
