name: PRs to main
on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-main-to-stage:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
    - name: Merge main to stage
      run: |
          git fetch
          git checkout stage
          git pull
          git merge --no-ff main -m "Auto-merge main to stage"
          git push
