name: Update Codecov
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v2
