name: High Impact Alert

on:
  pull_request_target:
    types:
      - labeled

env:
  SLACK_HIGH_IMPACT_PR_WEBHOOK: ${{ secrets.SLACK_HIGH_IMPACT_PR_WEBHOOK }}
  SLACK_MILO_UPDATES_WEBHOOK: ${{ secrets.SLACK_MILO_UPDATES_WEBHOOK }}

jobs:
  send_alert:
    if: github.repository_owner == 'adobecom'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Send Slack message for high impact PRs
        uses: actions/github-script@v7
        with:
          script: |
            const main = require('./.github/workflows/high-impact-alert.js')
            main({ github, context })
