name: Manual Merge

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'stage' || github.event.pull_request.base.ref == 'main') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Notify Merge with GitHub Script
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const notifyMerge = require('./.github/workflows/pr-manual-merge.js');
            await notifyMerge({ github, context });
        env:
          MILO_RELEASE_SLACK_WH: ${{ secrets.MILO_RELEASE_SLACK_WH }}
