name: Create a Release for Standalone Feds GlobalNav and Footer
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-feds:
    name: Release Standalone Feds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./libs/navigation
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Files
      run: node ./build.mjs

    - name: Generate tarball
      run: npm pack

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh release create "feds-standalone-v${{ inputs.version }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="@adobecom/standalone-feds v${{ inputs.version }} Release" \
              --generate-notes

    - name: Upload Files to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload "feds-standalone-v${{ inputs.version }}" "adobecom-standalone-feds-${{ inputs.version }}.tgz"
